uploads = []
outputs = []

[[generated]]
id = "V1MUpsL5ctxZsW8nPmZ6o"
uri = "file://artifacts/geo-quiz/public/regions/europe.png"
type = "image"
title = "europe hero"

[[generated]]
id = "QRzOr4UOWHW6_bQNJ9XNk"
uri = "file://artifacts/geo-quiz/public/regions/africa.png"
type = "image"
title = "africa hero"

[[generated]]
id = "0P9Gzv-wifQSb-c-xzrtU"
uri = "file://artifacts/geo-quiz/public/regions/antarctica.png"
type = "image"
title = "antarctica hero"

[[generated]]
id = "KFoU3edsl7xM1z4e0O-Pf"
uri = "file://artifacts/geo-quiz/public/regions/middle-east.png"
type = "image"
title = "middle-east hero"

[[generated]]
id = "MsAdfgr-u3b4rnzyTZUI8"
uri = "file://artifacts/geo-quiz/public/regions/east-asia.png"
type = "image"
title = "east-asia hero"

[[generated]]
id = "A6UagLRbzBIB2wUioTF7Q"
uri = "file://artifacts/geo-quiz/public/regions/south-east-asia.png"
type = "image"
title = "south-east-asia hero"

[[generated]]
id = "AISapBxMMwSaCev-yl2tZ"
uri = "file://artifacts/geo-quiz/public/regions/oceania.png"
type = "image"
title = "oceania hero"

[[generated]]
id = "e3z7chutYbJ6BstkLsqE9"
uri = "file://artifacts/geo-quiz/public/regions/north-america.png"
type = "image"
title = "north-america hero"

[[generated]]
id = "ETkIewxXVIXbRJUN8Jc5p"
uri = "file://artifacts/geo-quiz/public/regions/central-america.png"
type = "image"
title = "central-america hero"

[[generated]]
id = "rHF-n0p-RsVGwRlxyTuuU"
uri = "file://artifacts/geo-quiz/public/regions/south-america.png"
type = "image"
title = "south-america hero"

[[generated]]
id = "NvQ5whWvJOtakNXkrNrvs"
uri = "file://artifacts/geo-quiz/public/regions/caribbean.png"
type = "image"
title = "caribbean hero"

[[generated]]
id = "HAIfhDxliSuW2vpnjaD8e"
uri = "file://artifacts/geo-quiz/public/regions/capitals.png"
type = "image"
title = "capitals hero"

[[generated]]
id = "G8JOx2L-CaVmHQbege4qf"
uri = "file://artifacts/geo-quiz/public/regions/physical-geography.png"
type = "image"
title = "physical-geography hero"

[[generated]]
id = "odHJEskZfkkrDlKEmXVpG"
uri = "file://artifacts/geo-quiz/public/regions/ancient-sites.png"
type = "image"
title = "ancient-sites hero"

[[generated]]
id = "LUwetIRoZUjwUj935RJV-"
uri = "file://artifacts/geo-quiz/public/regions/flags.png"
type = "image"
title = "world flags collage"

[[generated]]
id = "IoUOh8mLT8ma_sVkgrRr9"
uri = "file://artifacts/geo-quiz/public/regions/countries.png"
type = "image"
title = "countries world map"

[[generated]]
id = "_e_IcCHVLnoN7Pw_CiIAn"
uri = "file://artifacts/geo-quiz/public/regions/lakes-and-rivers.png"
type = "image"
title = "lakes and rivers"

[[generated]]
id = "0UaBe59BvY8tXM8MEXWNX"
uri = "file://artifacts/geo-quiz/public/regions/landmarks.png"
type = "image"
title = "world landmarks collage"

[[generated]]
id = "WCGZdNyU4uNbf_2_5530l"
uri = "file://artifacts/geo-quiz/public/regions/oceans-and-seas.png"
type = "image"
title = "oceans and seas"
